name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set executable permissions for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean install
  
      - name: Build the application
        run: |
          ./mvnw clean package -DskipTests

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          
      - name: Test SSH Connection
        run: ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "echo Connected!"
   
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/zendly-back || git clone https://github.com/wilsup2004/zendly-back.git && cd zendly-back
            git pull origin main
            ./mvnw clean package -DskipTests
            sudo docker stop spring-app || true
            sudo docker rm spring-app || true
            sudo docker run -d --name spring-app -p 8081:8081 -v ~/zendly-back:/app openjdk:17 java -jar /app/target/*.jar
